from OldHangeul import OLD_TEXTS
from OldHangeul import OLD_TEXTS


worddict = {
    OLD_TEXTS('을'): '가을',
    OLD_TEXTS('나리'): '시내',
    OLD_TEXTS('소반'): '밥상',
    OLD_TEXTS('바래'): '바다에',
    OLD_TEXTS('즈'): '모습을',
    OLD_TEXTS('즈믄'): '천',
    OLD_TEXTS('별해'): '벼랑에',
    OLD_TEXTS('해동(동방)'): '우리나라',
    OLD_TEXTS('곶()'): '꽃',
    OLD_TEXTS('녀름'): '여름',
    OLD_TEXTS('(가)'): '강',
    OLD_TEXTS('촉(燭)'): '촛불',
    OLD_TEXTS('남여'): '가마',
    OLD_TEXTS('녹양'): '버드나무',
    OLD_TEXTS('황앵'): '꾀꼬리',
    OLD_TEXTS('세우'): '가랑비',
    OLD_TEXTS('금수'): '수 놓은 비단',
    OLD_TEXTS('조화옹'): '조물주',
    OLD_TEXTS('삼공'): '삼정승',
    OLD_TEXTS('만승'): '천자',
    OLD_TEXTS('백구'): '흰 갈매기',
    OLD_TEXTS('이화'): '배꽃',
    OLD_TEXTS('도화'): '복숭아꽃',
    OLD_TEXTS('행화'): '살구꽃',
    OLD_TEXTS('두견화'): '진달래꽃',
    OLD_TEXTS('척촉'): '철쭉',
    OLD_TEXTS('연하'): '안개와 노을',
    OLD_TEXTS('혜음(헴)'): '생각',
    OLD_TEXTS('뫼'): '산, 수라',
    OLD_TEXTS('하얌(향암)'): '세상 이치를 모르는 어리석은 사람',
    OLD_TEXTS('소'): '연못',
    OLD_TEXTS('청약립'): '갓',
    OLD_TEXTS('녹사의'): '우비',
    OLD_TEXTS('건곤'): '하늘과 땅',
    OLD_TEXTS('믈'): '물',
    OLD_TEXTS('시비'): '사립문',
    OLD_TEXTS('실솔'): '귀뚜라미',
    OLD_TEXTS('모옥'): '초가',
    OLD_TEXTS('애()'): '날개',
    OLD_TEXTS('이'): '아양',
    OLD_TEXTS('시앗'): '첩',
    OLD_TEXTS('침선'): '바느질',
    OLD_TEXTS('수품'): '솜씨',
    OLD_TEXTS('()'): '마을',
    OLD_TEXTS('우음'): '웃음',
    OLD_TEXTS('흥진'): '속세',
    OLD_TEXTS('노화'): '갈대',
    OLD_TEXTS('죽장망혜'): '대지팡이와 짚신',
    OLD_TEXTS('도롱이'): '우비',
    OLD_TEXTS('벽계(벽계수)'): '푸른 시냇물'
}